import os
import copy
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.nn.utils.rnn import pad_sequence


class BaselineRNN(nn.Module):
    """
    Standard shared RNN for all participants.
    """
    def __init__(self, input_dim, hidden_dim, output_dim, num_layer=1, nonlinearity="tanh"):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.nonlinearity = nonlinearity

        self.rnn = nn.RNN(
            input_size=input_dim,
            hidden_size=hidden_dim,
            num_layers=num_layer,
            nonlinearity=nonlinearity,
            batch_first=True
        )
        self.output = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, participant_ids=None, h0=None):
        """
        x: [B, T, D]
        participant_ids: ignored, kept only for interface compatibility
        h0: optional initial hidden state [1, B, H]
        """
        h_all, h_n = self.rnn(x, h0)          # h_all: [B, T, H]
        logits = self.output(h_all)           # [B, T, C]
        return logits, h_n


class BaselineLSTM(nn.Module):
    def __init__(self, input_dim, hidden_dim, output_dim):
        super().__init__()
        self.hidden_dim = hidden_dim

        self.lstm = nn.LSTM(
            input_size=input_dim,
            hidden_size=hidden_dim,
            batch_first=True
        )
        self.output = nn.Linear(hidden_dim, output_dim)

    def forward(self, x, participant_ids=None):
        """
        x: [B, T, D]
        participant_ids: ignored, included only for interface compatibility
        """
        h, _ = self.lstm(x)                  # [B, T, H]
        logits = self.output(h)             # [B, T, C]
        return logits, None



class HyperRNN(nn.Module):
    """
    Participant-conditioned RNN with:
        W_hh(participant) = W_hh_base + delta_W_hh(participant)

    Shared across participants:
        - input-to-hidden weights
        - base recurrent matrix
        - hidden bias
        - output layer

    Participant-specific:
        - delta_W_hh generated by hypernetwork from participant embedding
    """
    def __init__(
        self,
        n_participants: int,
        input_dim: int,
        hidden_dim: int,
        output_dim: int,
        participant_emb_dim: int = 16,
        hyper_hidden_dim: int = 64,
        nonlinearity: str = "tanh",
    ):
        super().__init__()

        if nonlinearity not in {"tanh", "relu"}:
            raise ValueError("nonlinearity must be 'tanh' or 'relu'")

        self.n_participants = n_participants
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.participant_emb_dim = participant_emb_dim
        self.nonlinearity = nonlinearity

        self.participant_embedding = nn.Embedding(n_participants, participant_emb_dim)

        # shared parameters
        self.b_x = nn.Parameter(torch.zeros(hidden_dim))  # just to be consistent with PyTorch RNN implementation
        self.W_xh = nn.Parameter(torch.empty(hidden_dim, input_dim))
        self.W_hh_base = nn.Parameter(torch.empty(hidden_dim, hidden_dim))
        self.b_h = nn.Parameter(torch.zeros(hidden_dim))

        self.W_hy = nn.Parameter(torch.empty(output_dim, hidden_dim))
        self.b_y = nn.Parameter(torch.zeros(output_dim))

        # hypernetwork outputs delta_W_hh, not full W_hh
        hyper_out_dim = hidden_dim * hidden_dim
        self.hypernet = nn.Sequential(
            nn.Linear(participant_emb_dim, hyper_hidden_dim),
            nn.ReLU(),
            nn.Linear(hyper_hidden_dim, hyper_out_dim),
        )

        self.reset_parameters()

    def reset_parameters(self):
        nn.init.zeros_(self.b_x)
        nn.init.xavier_uniform_(self.W_xh)
        nn.init.orthogonal_(self.W_hh_base)
        nn.init.zeros_(self.b_h)

        nn.init.xavier_uniform_(self.W_hy)
        nn.init.zeros_(self.b_y)

        nn.init.normal_(self.participant_embedding.weight, mean=0.0, std=0.02)

        # initialize the first layer of the hypernetwork with Kaiming uniform for better training stability
        nn.init.kaiming_uniform_(self.hypernet[0].weight, nonlinearity="relu")
        nn.init.zeros_(self.hypernet[0].bias)

        # initialize the second layer of the hypernetwork to produce small initial delta_W_hh
        nn.init.zeros_(self.hypernet[2].weight)
        nn.init.zeros_(self.hypernet[2].bias)

    def generate_delta_W_hh(self, participant_ids: torch.Tensor) -> torch.Tensor:
        batch_size = participant_ids.size(0)
        z = self.participant_embedding(participant_ids)              # [B, E]
        hyper_out = self.hypernet(z)                                # [B, H*H]
        delta_W_hh = hyper_out.view(batch_size, self.hidden_dim, self.hidden_dim)
        return delta_W_hh

    def recurrent_nonlinearity(self, x):
        if self.nonlinearity == "tanh":
            return torch.tanh(x)
        return F.relu(x)

    def forward(self, x: torch.Tensor, participant_ids: torch.Tensor, h0=None):
        """
        x: [B, T, D]
        participant_ids: [B]
        h0: [B, H] or None
        """
        batch_size, seq_len, _ = x.shape
        device = x.device

        if h0 is None:
            h_t = torch.zeros(batch_size, self.hidden_dim, device=device)
        else:
            h_t = h0

        delta_W_hh = self.generate_delta_W_hh(participant_ids)      # [B, H, H]
        W_hh = self.W_hh_base.unsqueeze(0) + delta_W_hh             # [B, H, H]

        logits_all = []

        for t in range(seq_len):
            x_t = x[:, t, :]                                        # [B, D]
            x_proj = F.linear(x_t, self.W_xh, self.b_x)                       # [B, H]
            h_proj = torch.bmm(W_hh, h_t.unsqueeze(-1)).squeeze(-1) # [B, H]

            h_t = self.recurrent_nonlinearity(x_proj + h_proj + self.b_h)

            logits_t = F.linear(h_t, self.W_hy, self.b_y)           # [B, C]
            logits_all.append(logits_t.unsqueeze(1))

        logits_all = torch.cat(logits_all, dim=1)                   # [B, T, C]
        return logits_all, h_t


class HyperLSTM(nn.Module):
    def __init__(
        self,
        n_participants: int,
        input_dim: int,
        hidden_dim: int,
        output_dim: int,
        participant_emb_dim: int = 16,
        rank: int = 4,
        hyper_hidden_dim: int = 32,
    ):
        super().__init__()

        self.n_participants = n_participants
        self.input_dim = input_dim
        self.hidden_dim = hidden_dim
        self.output_dim = output_dim
        self.participant_emb_dim = participant_emb_dim
        self.rank = rank

        self.participant_embedding = nn.Embedding(
            n_participants, participant_emb_dim
        )

        self.W_xh = nn.Parameter(torch.randn(4 * hidden_dim, input_dim) * 0.1)
        self.W_hh_base = nn.Parameter(torch.randn(4 * hidden_dim, hidden_dim) * 0.1)
        self.b = nn.Parameter(torch.zeros(4 * hidden_dim))

        self.W_hy = nn.Parameter(torch.randn(output_dim, hidden_dim) * 0.1)
        self.b_y = nn.Parameter(torch.zeros(output_dim))

        hyper_out_dim = (4 * hidden_dim * rank) + (hidden_dim * rank)

        self.hypernet = nn.Sequential(
            nn.Linear(participant_emb_dim, hyper_hidden_dim),
            nn.ReLU(),
            nn.Linear(hyper_hidden_dim, hyper_out_dim),
        )

        with torch.no_grad():
            self.b[:hidden_dim].fill_(1.0)  # initialize forget gate bias

    def generate_delta_W_hh(self, participant_ids: torch.Tensor) -> torch.Tensor:
        batch_size = participant_ids.size(0)
        z = self.participant_embedding(participant_ids)
        hyper_out = self.hypernet(z)

        a_size = 4 * self.hidden_dim * self.rank
        b_size = self.hidden_dim * self.rank

        A_flat = hyper_out[:, :a_size]
        B_flat = hyper_out[:, a_size:a_size + b_size]

        A = A_flat.view(batch_size, 4 * self.hidden_dim, self.rank)
        B = B_flat.view(batch_size, self.hidden_dim, self.rank)

        delta_W = torch.bmm(A, B.transpose(1, 2))  # [B, 4H, H]
        return delta_W

    def forward(self, x: torch.Tensor, participant_ids: torch.Tensor, hc=None):
        batch_size, seq_len, _ = x.shape
        device = x.device

        if hc is None:
            h_t = torch.zeros(batch_size, self.hidden_dim, device=device)
            c_t = torch.zeros(batch_size, self.hidden_dim, device=device)
        else:
            h_t, c_t = hc

        delta_W_hh = self.generate_delta_W_hh(participant_ids)
        W_hh = self.W_hh_base.unsqueeze(0) + delta_W_hh

        logits_all = []

        for t in range(seq_len):
            x_t = x[:, t, :]

            gates_x = F.linear(x_t, self.W_xh)
            gates_h = torch.bmm(W_hh, h_t.unsqueeze(-1)).squeeze(-1)
            gates = gates_x + gates_h + self.b

            f_t, i_t, g_t, o_t = gates.chunk(4, dim=1)

            f_t = torch.sigmoid(f_t)
            i_t = torch.sigmoid(i_t)
            g_t = torch.tanh(g_t)
            o_t = torch.sigmoid(o_t)

            c_t = f_t * c_t + i_t * g_t
            h_t = o_t * torch.tanh(c_t)

            logits_t = F.linear(h_t, self.W_hy, self.b_y)
            logits_all.append(logits_t.unsqueeze(1))

        logits_all = torch.cat(logits_all, dim=1)
        return logits_all, (h_t, c_t)


def sequence_nll_loss(logits, targets, mask=None):
    """
    logits:  [B, T, C]
    targets: [B, T]
    mask:    [B, T] with 1 for valid trials, 0 for padded trials

    Returns mean negative log-likelihood over valid sequence positions.
    """
    B, T, C = logits.shape
    logits_flat = logits.reshape(B * T, C)
    targets_flat = targets.reshape(B * T)

    # F.cross_entropy is equal to log_softmax + nll_loss, and it calculates NLL
    loss_per_item = F.cross_entropy(logits_flat, targets_flat, reduction="none")

    if mask is None:
        return loss_per_item.mean()

    mask_flat = mask.reshape(B * T).float()
    return (loss_per_item * mask_flat).sum() / mask_flat.sum().clamp_min(1.0)


def sequence_accuracy(logits, targets, mask=None):
    preds = logits.argmax(dim=-1)  # [B, T]
    correct = (preds == targets).float()

    if mask is None:
        return correct.mean().item()

    correct = correct * mask.float()
    return (correct.sum() / mask.sum().clamp_min(1.0)).item()


def train_one_epoch(model, dataloader, optimizer, device, model_type="baseline",
                    emb_reg=1e-4, hyper_reg=1e-5, max_grad_norm=1.0):
    model.train()

    total_loss = 0.0
    total_acc = 0.0
    n_batches = 0

    for batch in dataloader:
        x = batch['x'].to(device)                         # [B, T, D]
        y = batch['y'].to(device)                         # [B, T]
        participant_ids = batch['participant_id'].to(device)  # [B]
        mask = batch.get("mask", None)
        if mask is not None:
            mask = mask.to(device)

        optimizer.zero_grad()

        logits, _ = model(x, participant_ids)
        loss = sequence_nll_loss(logits, y, mask)

        # extra regularization only for hypernetwork model
        if model_type == "hyper":
            emb = model.participant_embedding(participant_ids)
            loss = loss + emb_reg * emb.pow(2).mean()

            delta_W = model.generate_delta_W_hh(participant_ids)
            loss = loss + hyper_reg * delta_W.pow(2).mean()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=max_grad_norm)
        optimizer.step()

        acc = sequence_accuracy(logits, y, mask)

        total_loss += loss.item()
        total_acc += acc
        n_batches += 1

    return {
        "loss": total_loss / max(n_batches, 1),
        "acc": total_acc / max(n_batches, 1),
    }


@torch.no_grad()
def evaluate(model, dataloader, device):
    model.eval()

    total_loss = 0.0
    total_acc = 0.0
    n_batches = 0

    for batch in dataloader:
        x = batch["x"].to(device)
        y = batch["y"].to(device)
        participant_ids = batch["participant_id"].to(device)
        mask = batch.get("mask", None)
        if mask is not None:
            mask = mask.to(device)

        logits, _ = model(x, participant_ids)
        loss = sequence_nll_loss(logits, y, mask)

        acc = sequence_accuracy(logits, y, mask)

        total_loss += loss.item()
        total_acc += acc
        n_batches += 1

    return {
        "raw_loss": total_loss / max(n_batches, 1),
        "acc": total_acc / max(n_batches, 1),
    }


def fit_model(
    model,
    train_loader,
    val_loader,
    n_epochs,
    device,
    save_path,
    model_type="baseline",
    lr=1e-3,
    emb_reg=1e-4,
    hyper_reg=1e-5,
    max_grad_norm=1.0,
    patience=10,
    min_delta=1e-4,
    extra_config=None,
):
    """
    Train one model, keep the best validation checkpoint, apply early stopping,
    and save the best checkpoint.

    Early stopping rule:
        stop if validation loss does not improve by at least `min_delta`
        for `patience` consecutive epochs.

    Returns:
        model, history, best_val_loss
    """
    model = model.to(device)
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float("inf")
    best_state = None
    best_epoch = 0
    epochs_without_improvement = 0
    history = []

    for epoch in range(1, n_epochs + 1):
        train_metrics = train_one_epoch(
            model=model,
            dataloader=train_loader,
            optimizer=optimizer,
            device=device,
            model_type=model_type,
            emb_reg=emb_reg,
            hyper_reg=hyper_reg,
            max_grad_norm=max_grad_norm,
        )

        val_metrics = evaluate(
            model=model,
            dataloader=val_loader,
            device=device,
        )

        history.append({
            "epoch": epoch,
            "train_loss": train_metrics["loss"],
            "train_acc": train_metrics["acc"],
            "val_loss": val_metrics["raw_loss"],
            "val_acc": val_metrics["acc"],
        })

        print(
            f"Epoch {epoch:03d} | "
            f"train loss={train_metrics['loss']:.4f}, acc={train_metrics['acc']:.4f} | "
            f"val loss={val_metrics['raw_loss']:.4f}, acc={val_metrics['acc']:.4f}"
        )

        # Improvement means val loss decreased by at least min_delta
        if val_metrics["raw_loss"] < (best_val_loss - min_delta):
            best_val_loss = val_metrics["raw_loss"]
            best_state = copy.deepcopy(model.state_dict())
            best_epoch = epoch
            epochs_without_improvement = 0
        else:
            epochs_without_improvement += 1

        if epochs_without_improvement >= patience:
            print(
                f"Early stopping triggered at epoch {epoch}. "
                f"Best epoch was {best_epoch} with val loss {best_val_loss:.4f}."
            )
            break

    # restore best checkpoint into model
    if best_state is not None:
        model.load_state_dict(best_state)

    checkpoint = {
        "model_state_dict": best_state,
        "best_val_loss": best_val_loss,
        "best_epoch": best_epoch,
        "history": history,
        "model_type": model_type,
        "patience": patience,
        "min_delta": min_delta,
        "extra_config": extra_config,
    }

    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    torch.save(checkpoint, save_path)
    print(f"Saved best checkpoint to: {save_path}")

    return model, history, best_val_loss


def load_checkpoint(model, checkpoint_path, device):
    """
    Load a saved checkpoint into an already-instantiated model.
    Returns:
        model, checkpoint
    """
    checkpoint = torch.load(checkpoint_path, map_location=device)
    model.load_state_dict(checkpoint["model_state_dict"])
    model = model.to(device)
    print(f"Loaded checkpoint from: {checkpoint_path}")
    return model, checkpoint


@torch.no_grad()
def test_model(
    model,
    test_loader,
    device,
):
    """
    Evaluate a trained model on the test set.
    """
    test_metrics = evaluate(
        model=model,
        dataloader=test_loader,
        device=device
    )

    print(
        f"Test loss={test_metrics['raw_loss']:.4f}, "
        f"test acc={test_metrics['acc']:.4f}"
    )
    return test_metrics


class BehavioralDataset(Dataset):
    def __init__(self, dataframe, x_var, y_var):
        self.data = []

        for p_id, group in dataframe.groupby("participant_id"):
            group = group.sort_values("trial").reset_index(drop=True)

            x_vals = group[x_var].values.astype("float32")
            y_vals = group[y_var].values.astype("int64")

            self.data.append({
                "x": torch.tensor(x_vals, dtype=torch.float32),
                "y": torch.tensor(y_vals, dtype=torch.long),
                "participant_id": torch.tensor(p_id, dtype=torch.long),
            })

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]


def split_by_participant_trials(df, train_prop=0.70, val_prop=0.15):
    train_list, val_list, test_list = [], [], []

    for pid, group in df.groupby("participant_id"):
        group = group.sort_values("trial").reset_index(drop=True)

        n = len(group)
        train_end = int(n * train_prop)
        val_end = int(n * (train_prop + val_prop))

        train_list.append(group.iloc[:train_end])
        val_list.append(group.iloc[train_end:val_end])
        test_list.append(group.iloc[val_end:])

    return (
        pd.concat(train_list, ignore_index=True),
        pd.concat(val_list, ignore_index=True),
        pd.concat(test_list, ignore_index=True),
    )


def behavioral_collate_fn(batch):
    x_list = [item["x"] for item in batch]
    y_list = [item["y"] for item in batch]
    participant_ids = torch.stack([item["participant_id"] for item in batch])

    lengths = torch.tensor([x.shape[0] for x in x_list])

    x_padded = pad_sequence(
        x_list,
        batch_first=True,
        padding_value=0.0
    )

    y_padded = pad_sequence(
        y_list,
        batch_first=True,
        padding_value=0
    )

    mask = torch.arange(x_padded.size(1))[None, :] < lengths[:, None]

    return {
        "x": x_padded,                      # [B, T_max, D]
        "y": y_padded,                      # [B, T_max]
        "participant_id": participant_ids,  # [B]
        "mask": mask                        # [B, T_max]
    }


def collect_predictions(model, loader, device, threshold=0.5):
    model.eval()
    ys, probs = [], []

    with torch.no_grad():
        for batch in loader:
            x = batch["x"].to(device)
            y = batch["y"].to(device)
            pid = batch["participant_id"].to(device)
            mask = batch["mask"].to(device)

            logits, _ = model(x, pid)
            prob_correct = torch.softmax(logits, dim=-1)[..., 1]

            ys.append(y[mask].cpu())
            probs.append(prob_correct[mask].cpu())

    y_true = torch.cat(ys).numpy()
    p_correct = torch.cat(probs).numpy()
    y_pred = (p_correct >= threshold).astype(int)

    return y_true, y_pred, p_correct